language: python
sudo: required
dist: xenial

python:
    - "3.6"
    - "3.7"

services:
  - xvfb

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH

install:
    - conda create -n conda_test_env --yes python=$TRAVIS_PYTHON_VERSION
    - source activate conda_test_env
    - conda install --yes scipy pandas matplotlib cython numba pytest nbconvert ipykernel ipywidgets seaborn
    - conda config --append channels conda-forge
    - conda install --yes lmfit
    - conda install --yes phconvert
    - pip install pybroom
    - python setup.py build
    - pip install .
    - rm -rf build/

before_script:
    - mkdir notebooks/data
    - cd notebooks/data
    - wget -N http://files.figshare.com/2182604/12d_New_30p_320mW_steer_3.hdf5
    - wget -N http://files.figshare.com/2182601/0023uLRpitc_NTP_20dT_0.5GndCl.hdf5
    - cd ../..

script:
    - python -Wd fretbursts/tests/importtest.py
    - py.test -v
    - cd notebooks
    - python ../fretbursts/tests/nbrun.py --exclude-list dev/exclude-py27.txt .

sudo: false
